<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <ImportWindowsDesktopTargets>true</ImportWindowsDesktopTargets>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Esri.ArcGISRuntime" Version="300.1.0" />
    <PackageReference Include="Esri.ArcGISRuntime.Hydrography" Version="300.1.0" />
    <PackageReference Include="Esri.ArcGISRuntime.WPF" Version="300.1.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
    <PackageReference Include="System.Configuration.ConfigurationManager" Version="10.0.11" />
  </ItemGroup>
  <ItemGroup>
    <AppDesigner Include="Properties\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\gsi.png" />
  </ItemGroup>
  <ItemGroup>
    <Folder Include="System\Drawing\" />
  </ItemGroup>
  <ItemGroup>
    <Resource Include="Assets\ArcGISImagery.png" />
    <Resource Include="Assets\ArcGISOceans.png" />
    <Resource Include="Assets\ArcGISStreets.png" />
    <Resource Include="Assets\ArcGISTopographic.png" />
    <Resource Include="Assets\OSMStandard.png" />
  </ItemGroup>
</Project>